### ISSUE TITLE
Latest MEZ (26-Aug-2021) not getting recognized in PBI Desktop

### ISSUE THREAD

**Issue by Sh5678** [migueesc123/PowerBIRESTAPI#83] opened 2021-09-01 01:43 UTC
Hello - I downloaded the latest MEZ file (made available on 26-Aug-2021) but it is not getting recognized in my Jun-2021 version of PBI Desktop. 

But if I reverted to the prior version of MEZ file, it is getting recognized in PBI Desktop without any issue.

- Is there any issue with the latest MEZ file uploaded to GITHUB?

OR 

- Does it have any PBI Desktop version requirement, wherein it is not working with Jun-2021 version of PBI Desktop?

Appreciate having this made available and thanks in advance for resolving the above issue.

**Comment by klinejordan** [comment] 2021-09-07 22:59
I can't reproduce this issue and I'm using the latest .mez file and both the June and the August version of Power BI Desktop

**Comment by migueesc123** [comment] 2021-09-12 17:59
same here. Can't repro. 

@Sh5678 are you able to repro this on multiple environments? Could it be that your security settings prevent "uncertified" connectors from loading or any other specific local setting that prevents our connector to load?

**Comment by Sh5678** [comment] 2021-09-15 00:37
I have tried so far in 3 different machines:
M/c #1 -- With Jun-2021 PBI Desktop installed and subsequently with PBI Desktop upgraded to Jul-2021 version.
M/c #2 -- With Mar-2021 PBI Desktop installed
M/c #3 -- With May-2021 PBI Desktop installed

In every instance, if I download the file (https://github.com/migueesc123/PowerBIRESTAPI/blob/master/Power%20BI%20API.mez) and place it within the Custom Connectors directory, the Power BI API connector does not show up in the list or in search results.

But if I revert back the earlier version of "Power BI API.mez" (from my local backup), the earlier version of the API connector does show up within in Power-BI Desktop -- with Experimental (3), Functions (3), Gateways (3), Personal Workspace (5), Power BI Service Administrator (7), Workspaces (11).

Hope this also clears the above question on my security setting -- as the earlier version of the API connector does show up.

Attaching the version of the 2 files I've been using, for reference..
[PowerBIAPI Connectors.zip](https://github.com/migueesc123/PowerBIRESTAPI/files/7165859/PowerBIAPI.Connectors.zip)

**Comment by migueesc123** [comment] 2021-09-15 00:48
That's pretty odd. I'm baffled as it should just work. I'm not sure what could be happening, but there's really no action that we could take whatsoever - there's nothing at the code level of the connector to address this sort of situation.

Have you tried other custom connectors besides this one? Do they also have the same issue ?

I recently bought a new laptop and I don't have any issues loading the custom connector.

I've never heard or seen a situation like this ever before either. If you can't repro this issue with any other custom connectors, then there's really something odd happening with our specific connector, but I can't really tell what that might be.

**Comment by Chris-Burgess-ACTGOV** [comment] 2021-09-15 03:39
> I have tried so far in 3 different machines:
> M/c #1 -- With Jun-2021 PBI Desktop installed and subsequently with PBI Desktop upgraded to Jul-2021 version.
> M/c #2 -- With Mar-2021 PBI Desktop installed
> M/c #3 -- With May-2021 PBI Desktop installed
> 
> In every instance, if I download the file (https://github.com/migueesc123/PowerBIRESTAPI/blob/master/Power%20BI%20API.mez) and place it within the Custom Connectors directory, the Power BI API connector does not show up in the list or in search results.
> 
> But if I revert back the earlier version of "Power BI API.mez" (from my local backup), the earlier version of the API connector does show up within in Power-BI Desktop -- with Experimental (3), Functions (3), Gateways (3), Personal Workspace (5), Power BI Service Administrator (7), Workspaces (11).
> 
> Hope this also clears the above question on my security setting -- as the earlier version of the API connector does show up.
> 
> Attaching the version of the 2 files I've been using, for reference..
> [PowerBIAPI Connectors.zip](https://github.com/migueesc123/PowerBIRESTAPI/files/7165859/PowerBIAPI.Connectors.zip)

Just for clarity PBI is installed from download and not MS Store? There are some issues with 'user settings' I believe.
Secondly where are you storing the *.mez ?
C:\Users\mes\OneDrive - Business\Documents\Microsoft Power BI Desktop\Custom Connectors ?
C:\Users\me\Documents\Microsoft Power BI Desktop\Custom Connectors?

Had issues when we migrated 'home drives' to onedrive here.
And of course Data Extensions allowed in Global Security settings on each of the installations

May not be relevant.....especially if you have the two mez versions in same location and the PBI install can only see the older one

**Comment by Sh5678** [comment] 2021-09-15 18:49
> > I have tried so far in 3 different machines:
> > M/c #1 -- With Jun-2021 PBI Desktop installed and subsequently with PBI Desktop upgraded to Jul-2021 version.
> > M/c #2 -- With Mar-2021 PBI Desktop installed
> > M/c #3 -- With May-2021 PBI Desktop installed
> > In every instance, if I download the file (https://github.com/migueesc123/PowerBIRESTAPI/blob/master/Power%20BI%20API.mez) and place it within the Custom Connectors directory, the Power BI API connector does not show up in the list or in search results.
> > But if I revert back the earlier version of "Power BI API.mez" (from my local backup), the earlier version of the API connector does show up within in Power-BI Desktop -- with Experimental (3), Functions (3), Gateways (3), Personal Workspace (5), Power BI Service Administrator (7), Workspaces (11).
> > Hope this also clears the above question on my security setting -- as the earlier version of the API connector does show up.
> > Attaching the version of the 2 files I've been using, for reference..
> > [PowerBIAPI Connectors.zip](https://github.com/migueesc123/PowerBIRESTAPI/files/7165859/PowerBIAPI.Connectors.zip)
> 
> Just for clarity PBI is installed from download and not MS Store? There are some issues with 'user settings' I believe.
> Secondly where are you storing the *.mez ?
> C:\Users\mes\OneDrive - Business\Documents\Microsoft Power BI Desktop\Custom Connectors ?
> C:\Users\me\Documents\Microsoft Power BI Desktop\Custom Connectors?
> 
> Had issues when we migrated 'home drives' to onedrive here.
> And of course Data Extensions allowed in Global Security settings on each of the installations
> 
> May not be relevant.....especially if you have the two mez versions in same location and the PBI install can only see the older one

PBI Desktop mentioned are all installed 64 bit full version and not the Windows App from Microsoft Store
The MEZ file is placed in c:\users\<username>\Documents\Power BI Desktop\Custom Connectors folders
Although I had added 2 versions of the MEZ file in my earlier reply, I only keep 1 of them at any point of time within the above Custom Connectors folder while both the versions are backed up in a different folder

FYI -- I just tried in a 4th machine (home PC), having Mar-2021 PBI Desktop installed.. When I keep the latest MEZ file, it is not getting detected but if I replace with the earlier version of the MEZ file, that gets detected properly.

With this I have tried with multiple machines, with them being in different networks & using different userids.. The resultant observation is the same -- the latest MEZ file (downloaded from the main page) does not get recognized while the earlier version (available within the zip file I had attached in my earlier response, with the file name as "Power BI API_20210708.mez") once copied to the custom connectors folder & renamed as "Power BI API.mez" get recognized properly. And it shows [Experimental (3), Functions (3), Gateways (3), Personal Workspace (5), Power BI Service Administrator (7), Workspaces (11).]

Wonder what will be so unique with all the machines I have tested with that it presents an issue.. Thanks in advance for looking into this and valuable suggestions / solutions..

**Comment by migueesc123** [comment] 2021-09-15 18:54
But, does this happen with other custom connectors that you've tried ? Or is it only with this one ?

**Comment by Sh5678** [comment] 2021-09-15 19:03
> But, does this happen with other custom connectors that you've tried ? Or is it only with this one ?

This is the only custom connector I'm using.. 

Since one version is working but the latest is not - was there any specific difference between the earlier version & the latest version? 

Any other custom connector you recommend me to test with?

**Comment by migueesc123** [comment] 2021-09-15 19:06
You might need to do a diff between the one you're using and the latest one to see what exact version you might be using.

Any other connector that you want to try would be good. You can check the other repos that I have to see other connectors that I've created, but any other will do.

I've just created a new Azure VM running Windows 10 and this and other connectors get recognized without issues.

**Comment by migueesc123** [comment] 2021-09-18 23:30
Unfortunately, we don't have the resources to further investigate what's happening with your specific environments. 

What I'd encourage you to do is to provide us with a set of repro steps either by helping us create a new environment similar to yours or a specific set of steps that could work on a completely new install of Windows. One way to commonly do this is to use a VM service such as Azure or AWS and giving us a set of steps from the very start as to what specific OS image to use to create the environment.

i actually tried it this way by creating a completely new environment in Azure (a new virtual machine) with different specs and I've been unable to repro the issue.

My best guess at this point is that there might be something happening with how your specific environment has been setup. Perhaps regional settings, culture, or any other specific environment / registry settings which could affect multiple custom connectors and not just this one.

I'm closing this one for now, but will re-open once anyone provides a set of repro steps.

**Closed by migueesc123** 2021-09-18 23:30 UTC
Labels: cant-repro
