### ISSUE TITLE
Errors with tables in workspaces folder

### ISSUE THREAD

**Issue by Mlzbr1974** [migueesc123/PowerBIRESTAPI#85] opened 2021-09-12 14:29 UTC
Hello,

Thank you for the  api its awesome. 
I have an issue with all tables in workspace groupes (dashboard tiles, dashboards, ..all 14 tables) 
When i selected it, i have an error : 
**Expression error : Sorry we can't find column 1 from table;. Details : column 1 ******

Same issue with Gateway section : Can't find id colum from table
GetData & GetRawData : DataSource.Error : Web.contents can't get the content of "https//api.powerbi.com/v1.0/myorg 404 not found. 
DataSourceKind=PowerBIRESTAPI
DataSourcePath=PowerBIRESTAPI
Url=https://api.powerbi.com/v1.0/myorg

I have the rights of PowerBI admin

Could you help me?
Thank you

**Comment by migueesc123** [comment] 2021-09-12 17:25
Hey,

I can't repro. Are you able to repro that scenario in a different tenant? (if you have any)

I'd recommend using something like Fiddler to trace the calls that you're making against the REST API and see the exact response that you're getting from the API to check if you're getting the result that you're expecting. 

@ImkeF @klinejordan  Are you guys able to repro? Not sure what could be causing those sort of issues.

**Comment by Mlzbr1974** [comment] 2021-09-12 18:48
I try directly on my company network and same issue. 
I resolve the problem for the gateway (add user to gateway administrator) 
Same issue for the rest

**Comment by klinejordan** [comment] 2021-09-14 16:53
Just being a Power BI admin doesn't mean you'll be able to use the APIs in the Workspace group or the Gateway group. You'll be able to use the Power BI Administrator APIs, but not necessarily the other ones. 

For gateways, you need to be an admin on at least one gateway cluster for those APIs to return any information. 

For the Workspace group, you need to be a member of at least one workspace that's not your personal workspace. 

Have you met those prerequisites?

**Comment by Mlzbr1974** [comment] 2021-09-14 18:00
hello @klinejordan, 
Thank you for your message. 
I try the Power BI API with Admin Global and same issue. 
For the gateway, I wasnt registered, now its working fine. 
For the Workspace group, I dont now I will try sir. 
I let you know the issue.

**Comment by migueesc123** [comment] 2021-09-18 23:04
Thanks for the hindsight @klinejordan !

 I was able to repro that situation on a different tenant and its by-design how the API works. I'm closing this one as it appears to be working as intended.

**Closed by migueesc123** 2021-09-18 23:04 UTC
Labels: help wanted, cant-repro
